---
title: "CO Water Rights by district"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include = FALSE}
# Shiny & Flexdashboard packages
library(shiny)
library(flexdashboard)

# Data manipulation
# library(tidyr)
# library(dplyr)
library(dplyr)
library(ggplot2)
library(DT)
# Mapping packages
library(leaflet)
library(leafem)
library(dataRetrieval)
library(nhdplusTools)
# library(sf)

# water data
# library(nhdplusTools)
# library(cdssr)

# Load function data_utils.R file
source('utils.R')
```

```{r context="server"}
# water rights net amounts spatial data
wr_pts     <- readRDS("water_right_netamounts_pts.rds")
# uwdids     <- readRDS("data/unique_wdids.rds")
end_pts    <- readRDS("data/upstream_pts_district.rds")
# call_df    <- readRDS("data/upstream_call_analysis.rds")
# hucs       <- readRDS("data/huc4.rds")
# main_stem  <- readRDS("data/nhd_mainstems.rds")

dists      <- sf::read_sf("data/water_districts.gpkg") %>% 
  dplyr::mutate(
    new_id = DISTRICT,
    map_id = paste0("map_id_", new_id)
  )
# main_stem  <- readRDS("data/nhd_mainstems_district.rds")
# call_df    <- readRDS("data/upstream_call_analysis_district.rds")

# base leaflet map
output$baseMap       <- renderLeaflet({ dist_basemap(shp = dists) })

```

```{r context="server"}
map_click <- shiny::reactive({
   input$baseMap_click
})
```

```{r context="server"}
dist_id <- shiny::reactive({
   as.numeric(input$baseMap_shape_click$id)
})
```

<!-- # ```{r context="server"} -->
<!-- # call_ts <- shiny::reactive({ -->
<!-- #    call_df[call_df$wdid == end_pts[end_pts$district == dist_id(),]$wdid, ] -->
<!-- #   # call_df[call_df$wdid == end_pts[end_pts$district == "01",]$wdid, ] -->
<!-- #    # call_df[call_df$wdid == end_pts[end_pts$huc4 == "1019",]$wdid, ] -->
<!-- # }) -->
<!-- #  -->
<!-- # ``` -->

```{r context="server"}
sub_pts <- shiny::reactive({
   wr_pts[wr_pts$water_district == dist_id(),]
   # sub_pts <- wr_pts[wr_pts$water_district == as.numeric("06"),]
})
```

```{r context="server"}
dist_wdid <- shiny::reactive({
   sub_pts()$wdid
})

# cdss_data <- shiny::reactive({
#     if (!is.null(input$selectWDID)) {
#       cdssr::get_call_analysis_wdid(
#         wdid       = input$selectWDID,
#         admin_no   = "99999.00000",
#         start_date = Sys.Date() - 365*5,
#         end_date   = Sys.Date()
#         ) %>%
#         dplyr::mutate(
#           priority_date = dplyr::case_when(
#                             is.na(priority_date) ~ Sys.Date(),
#                             TRUE                 ~ as.Date(priority_date)
#                           )
#                         )
#     }
#   })
```

<!-- ```{r context="server"} -->
<!-- dist_wdid <- shiny::reactive({ -->
<!--    input$selectWDID -->
<!-- }) -->
<!-- ``` -->

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}

# shiny::selectInput(
#   "yearNum",
#   label = h3("Year"),
#   choices = 1990:2023,
#   selected = 2022
# )

shiny::selectizeInput(
  inputId  = "selectedYears",
  label    = h3("Year"),
  choices  = 2018:2022,
  selected = 2022,
  multiple = TRUE
  )
```

```{r}
shiny::selectizeInput(
  inputId  = "selectWDID",
  label    = h3("WDID"),
  # choices  = uwdids$wdid,
  choices  = NULL,
  selected = NULL,
  multiple = FALSE
  # options = list(plugins = list("remove_button"), 
  #                server = TRUE)
  )

shiny::observe({
 
  # Update the choices of input2 based on the reactive value
  shiny::updateSelectizeInput(session, "selectWDID", choices = dist_wdid())
   
})

```

1. Click on a HUC4 area within the interactive map in the top right panel

2. Adjust years of interest that will be highlighted in the top left plot.

<br>

The top left plot represents the most SENIOR right that makes a water right call throughout the year. Values lower on the Y axis correspond to a *more senior right* calling out. 

<br>

**The call analysis is done from the MOST upstream WDID at each HUC4's primary river mainstem using the most junior water right possible (admin number = "99999.00000").**  



Row
-------------------------------------

### Map 1
```{r}
leaflet::leafletOutput("baseMap")
```

```{r context="server"}
# Clicking on map 1 outputs Value boxes on both pages + catchment polygons + Dat table + success panel
# observeEvent(input$districtMapMLR_click, {
shiny::observeEvent(input$baseMap_shape_click, {

   if(is.null(dist_id())) {

     return(NULL)

   } else {

   # # if(!is.null(input$districtMapMLR_click)) {
   #    click <- input$districtMapMLR_click %>%
   #      data.frame() %>%
   #      dplyr::select(lat,lng)
      # print(click)

          pt <- sf::st_as_sf(
                    data.frame(
                      lat = map_click()$lat,
                      lng = map_click()$lng
                      ),
                    coords = c("lng", "lat"),
                    crs = 4326
                    )
          # 39.7792 -105.7214
          # 40.66392 -105.4837
          # 40.69808 -105.6
          # pt <- sf::st_as_sf(
          #           data.frame(
          #             lat = "39.978",
          #             lng =  "-105.6"
          #             ),
          #           coords = c("lng", "lat"),
          #           crs = 4326
          #           )

          print(paste0("Subsetting mainstems to HUC4: ",  dist_id()))

          print("Subsetting WDIDs to district area...")

          # subset to water district of interest
          sub_dist <- dists[dists$DISTRICT == dist_id(), ]
          
          
          # area_nhd <- nhdplusTools::get_nhdplus(
          #   AOI         = sub_dist,
          #   realization = c("flowline"),
          #   streamorder = 5
          #   )
          
          # nhdplusTools::navigate_network(
          #   start = pt, 
          #   
          # )
          
          
          # sub_pts  <- wr_pts[wr_pts$water_district == dist_id(), ]
          # sub_dist <- dists[dists$DISTRICT == as.numeric("06"), ]
          # sub_pts  <- wr_pts[wr_pts$water_district == as.numeric("06"), ]

          print("Updating leaflet map...")

          # dynamically alter leaflet map
          leaflet::leafletProxy("baseMap") %>%
              leaflet::clearMarkers() %>%
              leaflet::clearShapes() %>%
              leaflet::clearGroup(c("subdist")) %>%
                # leaflet::removeShape(layerId = levelpathi) %>%
                leaflet::addPolygons(
                      data         = dists,
                      fillColor    = 'white',
                      # fillColor = 'grey',
                      # fillColor = ~pal_fact(BASIN),
                      fillOpacity  = 0.7,
                      col          = "black",
                      opacity      = 1,
                      weight       = 2.5,
                      label        = ~paste0("District: ", DISTRICT),
                      layerId      = ~DISTRICT,
                      labelOptions = leaflet::labelOptions(
                                          noHide = F,
                                          style  = list(
                                            "color" = "black",
                                            "font-weight" = "1000")
                                        )
                  ) %>%
                leaflet::addPolygons(
                    data         = sub_dist,
                    fillColor    = '#3EB489',
                    # fillColor = 'grey',
                    # fillColor = ~pal_fact(BASIN),
                    fillOpacity  = 0.5,
                    col          = "black",
                    opacity      = 1,
                    weight       = 3,
                    group        = "subdist",
                    label        = ~paste0("District: ", DISTRICT),
                    layerId      = ~DISTRICT,
                    labelOptions = leaflet::labelOptions(
                                        noHide = F,
                                        style  = list(
                                          "color" = "black",
                                          "font-weight" = "1000")
                                      )
                ) %>%
              leaflet::addCircleMarkers(
                  data        = sub_pts(),
                  radius      = 6,
                  stroke      = FALSE,
                  color       = "black",
                  opacity     = 0.6,
                  fillColor   = "black",
                  fillOpacity = 0.6,
                  label       = ~paste0("WDID: ", wdid, " - ( Approp date: ", appropriation_date, " )"),
                  labelOptions = leaflet::labelOptions(
                                        noHide = F,
                                        style  = list(
                                          "color" = "black",
                                          "font-weight" = "1000")
                                      )
                  ) 
            # leaflet::addPolylines(
            #   data = area_nhd,
            #   color = "navy",
            #   opacity = 0.9,
            #   stroke = TRUE
            # )
              # leaflet::addCircleMarkers(
              #         data        = sub_pts()[sub_pts()$wdid == input$selectWDID, ],
              #         radius      = 10,
              #         stroke      = FALSE,
              #         color       = "red",
              #         opacity     = 1,
              #         fillColor   = "red",
              #         fillOpacity = 0.7
              #         ) 
            # leaflet::addCircleMarkers(
            #   data = sub_pts$
            #   
            # )
            
             shiny::observe({

                  if(is.null(input$selectWDID)) {

                       return(NULL)

                     } else {
                       # poi    <- sub_pts()[sub_pts()$wdid == input$selectWDID, ]
                
                       # dm_net <- nhdplusTools::navigate_network(
                       #                start       = area_nhd$outlet, 
                       #                mode        = "DM",
                       #                distance_km = 10
                       #                )
                       # area_nhd <- nhdplusTools::get_nhdplus(
                       #   AOI          = pt,
                       #    realization = c("flowline", "outlet")
                       #    streamorder = 4
                       #    )
                       
                    leaflet::leafletProxy("baseMap") %>%
                        leaflet::clearGroup(c("singleWDID")) %>%
                        leaflet::addCircleMarkers(
                            data        = sub_pts()[sub_pts()$wdid == input$selectWDID, ],
                            radius      = 10,
                            stroke      = FALSE,
                            color       = "red",
                            opacity     = 1,
                            fillColor   = "red",
                            group       = "singleWDID",
                            fillOpacity = 0.7,
                            label       = ~paste0("WDID: ", wdid, " - ( Approp date: ", appropriation_date, " )"),
                            labelOptions = leaflet::labelOptions(
                                        noHide = F,
                                        style  = list(
                                          "color" = "black",
                                          "font-weight" = "1200")
                                      )
                            )
                    
                   if (!is.null(input$selectWDID)) {
                     
                     print(input$selectWDID)
                     
                     if(input$selectWDID != "") {
                            
                           calls <- cdssr::get_call_analysis_wdid(
                                              wdid       = input$selectWDID,
                                              # wdid = "0200509",
                                              admin_no   = "99999.00000",
                                              start_date = Sys.Date() - 365*5,
                                              end_date   = Sys.Date()
                                            ) %>%
                                     dplyr::mutate(
                                              priority_date = dplyr::case_when(
                                                is.na(priority_date) ~ Sys.Date(),
                                                TRUE                 ~ as.Date(priority_date)
                                              )
                                              )

                              # min_date =  min(as.Date(sf::st_drop_geometry(wr_pts[wr_pts$wdid == "0200509", ])$appropriation_date))
                              min_date =  min(as.Date(sf::st_drop_geometry(wr_pts[wr_pts$wdid == input$selectWDID,
                                                                                  ])$appropriation_date))
                         # render call date over time plot
                         output$callDatePlot <- shiny::renderPlot({
  
                            make_single_call_plot(
                              df    = calls,
                              min_line = min_date, 
                              years = input$selectedYears
                              )
  
                            })

                     }
                   }
                     }
             })
              # leaflet::flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4])
            # shiny::observeEvent(input$selectWDID, {
          # shiny::observe({
          #       # Get the selected value of input1
          #       selected_input1 <- input$selectWDID
          #       # 
          #       # # Define the colors based on the selected value of input1
          #       colors <- ifelse(sub_pts()$id == selected_input1, "blue", "gray")
          #       
          #       print(paste0("Selectize input changed --> ", selected_input1))
          #       # Update the marker colors on the leaflet map
          #       leaflet::leafletProxy("baseMap") %>%
          #         leaflet::clearMarkers() %>%
          #         # leaflet::addCircleMarkers(
          #         #     data        = sub_pts()[sub_pts()$id != input$selectWDID,],
          #         #     radius      = 6,
          #         #     stroke      = FALSE,
          #         #     color       = "gray",
          #         #     opacity     = 1,
          #         #     fillOpacity = 0.7
          #         #     ) %>% 
          #         # leaflet::addCircleMarkers(
          #         #     data        = sub_pts()[sub_pts()$id == input$selectWDID,],
          #         #     radius      = 10,
          #         #     stroke      = FALSE,
          #         #     color       = "red",
          #         #     opacity     = 1,
          #         #     fillOpacity = 0.7
          #         #     ) 
          #           leaflet::addCircleMarkers(
          #             data        = sub_pts(),
          #             radius      = 10,
          #             stroke      = FALSE,
          #             # color       = "red",
          #             color = colors,
          #             opacity     = 1,
          #             fillOpacity = 0.7
          #             ) 
          #       })

          }
  })
# Listen to changes in the input value and update the marker color
# shiny::observe({
# shiny::observeEvent(input$selectWDID, {
#   # Get the selected value of input1
#   selected_input1 <- input$selectWDID
#   # 
#   # # Define the colors based on the selected value of input1
#   # colors <- ifelse(sub_pts()$id == selected_input1, "blue", "gray")
#   
#   print(paste0("Selectize input changed --> ", selected_input1))
#   # Update the marker colors on the leaflet map
#   leaflet::leafletProxy("baseMap") %>%
#     leaflet::clearMarkers() %>%
#     leaflet::addCircleMarkers(
#         data        = sub_pts()[sub_pts()$id != input$selectWDID,],
#         radius      = 6,
#         stroke      = FALSE,
#         color       = "gray",
#         opacity     = 1,
#         fillOpacity = 0.7
#         ) %>% 
#     leaflet::addCircleMarkers(
#         data        = sub_pts()[sub_pts()$id == input$selectWDID,],
#         radius      = 10,
#         stroke      = FALSE,
#         color       = "red",
#         opacity     = 1,
#         fillOpacity = 0.7
#         ) 
#   
# })

# shiny::observeEvent(input$selectWDID, {
# 
# 
#  calls <- cdssr::get_call_analysis_wdid(
#                                               wdid       = input$selectWDID,
#                                               # wdid = "0200509",
#                                               admin_no   = "99999.00000",
#                                               start_date = Sys.Date() - 365*5,
#                                               end_date   = Sys.Date()
#                                             ) %>% 
#                                      dplyr::mutate(
#                                               priority_date = dplyr::case_when(
#                                                 is.na(priority_date) ~ Sys.Date(),
#                                                 TRUE                 ~ as.Date(priority_date)
#                                               )
#                                             )
#                        # render call date over time plot 
#                        output$callDatePlot <- shiny::renderPlot({ 
#               
#                           make_single_call_plot(
#                             df    = calls,
#                             years = input$selectedYears
#                             ) 
#               
#                           }) 
#                        
# })
```

<!-- ### Coords  -->
<!-- ```{r} -->
<!-- shiny::verbatimTextOutput("mapCoords") -->
<!-- ``` -->

<!-- ```{r context="server"} -->

<!-- # render district value box at start -->
<!-- output$mapCoords <- shiny::renderPrint({ -->
<!--   print(data.frame( -->
<!--     lat = map_click()$lat, -->
<!--     lng = map_click()$lng -->
<!--     ) -->
<!--     ) -->
<!-- }) -->
<!-- ``` -->

<!-- ### distID output -->
<!-- ```{r} -->
<!-- shiny::verbatimTextOutput("distID") -->
<!-- ``` -->

<!-- ```{r context="server"} -->

<!-- # render district value box at start -->
<!-- output$distID <- shiny::renderPrint({ -->
<!--   print(dist_id()) -->
<!-- }) -->
<!-- ``` -->

Row
------------------------------------------------
### Table 
```{r}
DT::DTOutput("selectedWDIDinput")

```

```{r context="server"}

# render district value box at start
output$selectedWDIDinput <- DT::renderDT({
  
  # print(paste0("Selected WDID: ", input$selectWDID))
  # print("------------------------")
  
  # DT::datatable(sub_pts())
  # DT::datatable(sf::st_drop_geometry(sub_pts))
  DT::datatable(
    dplyr::select(sf::st_drop_geometry(sub_pts()), -comments),  
     fillContainer = TRUE,
      options       = list(
        pageLength   = 25,
        stateSave    = TRUE,
        lengthChange = FALSE,
        dom          = "ft"
        )
     #  ) %>%
     # DT::formatRound(columns = c('Latitude', 'Longitude'),  digits = 2)
    )
  # print("admin dates: ", cdss_data())
})
```

### Priority date vs. date (year facets)
```{r}
shiny::plotOutput("callDatePlot")
```


<!-- ### mnap 1 -->
<!-- ```{r} -->
<!-- # LHD leaflet output -->
<!-- leaflet::leafletOutput("baseMap") -->
<!-- ``` -->

<!-- ```{r context="server"} -->

<!-- # proxy <- leaflet::leafletProxy("baseMap") -->
<!-- #  -->
<!-- # selected <- shiny::reactiveValues(groups = vector()) -->
<!-- #  -->
<!-- # shiny::observeEvent(input$baseMap_shape_click, { -->
<!-- #       # print("observer1") -->
<!-- #       if(input$baseMap_shape_click$group == "regions") { -->
<!-- #          -->
<!-- #         selected$groups <- c(selected$groups, input$baseMap_shape_click$id) -->
<!-- #         print(paste0("selected group: ", selected$groups)) -->
<!-- #           proxy %>% -->
<!-- #             leaflet::showGroup(group = input$baseMap_shape_click$id) -->
<!-- #            -->
<!-- #           print("regions group click") -->
<!-- #       } else { -->
<!-- #          -->
<!-- #         selected$groups <- setdiff(selected$groups, input$baseMap_shape_click$group) -->
<!-- #         print(paste0("selected group: ", selected$groups)) -->
<!-- #  -->
<!-- #         proxy %>% -->
<!-- #           leaflet::hideGroup(group = input$baseMap_shape_click$group) -->
<!-- #         print("NOT regions group click") -->
<!-- #       } -->
<!-- #       # shiny::updateSelectizeInput( -->
<!-- #       #   session, -->
<!-- #       #   inputId  = "selected_locations", -->
<!-- #       #   label    = "Search", -->
<!-- #       #   choices  = unique(score_norm$new_id), -->
<!-- #       #   selected = selected$groups -->
<!-- #       #   ) -->
<!-- #     },ignoreNULL = TRUE) -->
<!-- ``` -->

