---
title: "CO Water Rights"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include = FALSE}
# Shiny & Flexdashboard packages
library(shiny)
library(flexdashboard)

# Data manipulation
# library(tidyr)
# library(dplyr)
library(dplyr)
library(ggplot2)

# Mapping packages
library(leaflet)
library(leafem)
library(dataRetrieval)
# library(sf)

# water data
# library(nhdplusTools)
# library(cdssr)

# Load function data_utils.R file
source('utils.R')
```

```{r context="server"}
# water rights net amounts spatial data
wr_pts     <- readRDS("water_right_netamounts_pts.rds")
end_pts    <- readRDS("data/upstream_pts_district.rds")
# call_df    <- readRDS("data/upstream_call_analysis.rds")
# hucs       <- readRDS("data/huc4.rds")
# main_stem  <- readRDS("data/nhd_mainstems.rds")

dists      <- sf::read_sf("data/water_districts.gpkg")
main_stem  <- readRDS("data/nhd_mainstems_district.rds")
call_df    <- readRDS("data/upstream_call_analysis_district.rds")

# base leaflet map
output$baseMap       <- renderLeaflet({ dist_basemap(shp = dists) })

```


```{r context="server"}
map_click <- shiny::reactive({
   input$baseMap_click
})
```

```{r context="server"}
dist_id <- shiny::reactive({
   as.numeric(input$baseMap_shape_click$id)
})
```

```{r context="server"}
call_ts <- shiny::reactive({
   call_df[call_df$wdid == end_pts[end_pts$district == dist_id(),]$wdid, ]
  # call_df[call_df$wdid == end_pts[end_pts$district == "01",]$wdid, ]
   # call_df[call_df$wdid == end_pts[end_pts$huc4 == "1019",]$wdid, ]
})

```
Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}

# shiny::selectInput(
#   "yearNum",
#   label = h3("Year"),
#   choices = 1990:2023,
#   selected = 2022
# )

shiny::selectizeInput(
  inputId  = "selectedYears",
  label    = h3("Year"),
  choices  = 1990:2022,
  selected = 2022,
  multiple = TRUE
  )
```

1. Click on a HUC4 area within the interactive map in the top right panel

2. Adjust years of interest that will be highlighted in the top left plot.

<br>

The top left plot represents the most SENIOR right that makes a water right call throughout the year. Values lower on the Y axis correspond to a *more senior right* calling out. 

<br>

**The call analysis is done from the MOST upstream WDID at each HUC4's primary river mainstem using the most junior water right possible (admin number = "99999.00000").**  



Row
-------------------------------------
### Map 1
```{r}
leaflet::leafletOutput("baseMap")
```

```{r context="server"}
# Clicking on map 1 outputs Value boxes on both pages + catchment polygons + Dat table + success panel
# observeEvent(input$districtMapMLR_click, {
shiny::observeEvent(input$baseMap_shape_click, {
  
   if(is.null(dist_id())) {
     
     return(NULL)
     
   } else {
     
   # # if(!is.null(input$districtMapMLR_click)) {
   #    click <- input$districtMapMLR_click %>%
   #      data.frame() %>%
   #      dplyr::select(lat,lng)
      # print(click)

          pt <- sf::st_as_sf(
                    data.frame(
                      lat = map_click()$lat,
                      lng = map_click()$lng
                      ),
                    coords = c("lng", "lat"),
                    crs = 4326
                    )
          # 39.7792 -105.7214
          # # 40.66392 -105.4837
          # 40.69808 -105.6
          # pt <- sf::st_as_sf(
          #           data.frame(
          #             lat = "40.69808",
          #             lng =  "-105.6"
          #             ),
          #           coords = c("lng", "lat"),
          #           crs = 4326
          #           )
          
          print(paste0("Subsetting mainstems to HUC4: ",  dist_id()))
          
          # select mainstem of HUC4 area
          fline <-
            main_stem %>%
            # dplyr::filter(district == dist_id())
            dplyr::filter(district == as.numeric("01"))
          # buffer bounds of mainstem for map fly to zoom
          bounds <-
            # buff %>%
            fline %>%
            # sf::st_buffer(5250) %>%
            sf::st_bbox() %>%
            as.vector()
 
          print("Buffering mainstem...")
          
          # buffer around mainstem to get points within
          fline_buff <- sf::st_as_sf(
                          sf::st_cast(
                            sf::st_union(
                              sf::st_buffer(
                                sf::st_transform(
                                  fline,
                                  5070
                                  ),
                                1609.3
                                )
                              ),
                            "POLYGON"
                            )
                          )
          
          print("Subsetting WDIDs to mainstem buffer...")

          # # # Water rights points around main flowline
          fline_pts <- sf::st_transform(
                          sf::st_filter(
                            sf::st_transform(
                              wr_pts,
                              5070
                              ) ,
                            fline_buff
                            ),
                            4326
                          )
          
          # subset to HUC4 of interest
          # sub_huc <- hucs[hucs$huc4 == huc_id(), ]
          # sub_dist <- dists[dists$DISTRICT == as.numeric("01"), ]
          sub_dist <- dists[dists$DISTRICT == dist_id(), ]
          
          print("Updating leaflet map...")
          
          # dynamically alter leaflet map 
          leaflet::leafletProxy("baseMap") %>%
              leaflet::clearMarkers() %>%
              leaflet::clearShapes() %>%
            leaflet::clearGroup(c("subhucs", "mainstems")) %>%
              # leaflet::removeShape(layerId = levelpathi) %>% 
              leaflet::addPolygons(
                    data         = dists,
                    fillColor    = 'white',
                    # fillColor = 'grey',
                    # fillColor = ~pal_fact(BASIN),
                    fillOpacity  = 0.7,
                    col          = "black",
                    opacity      = 1,
                    weight       = 2.5,
                    label        = ~paste0("District: ", DISTRICT),
                    layerId      = ~DISTRICT,
                    labelOptions = leaflet::labelOptions(
                                        noHide = F,
                                        style  = list(
                                          "color" = "black",
                                          "font-weight" = "1000")
                                      )
                ) %>%
              leaflet::addPolygons(
                  data         = sub_dist,
                  fillColor    = '#3EB489',
                  # fillColor = 'grey',
                  # fillColor = ~pal_fact(BASIN),
                  fillOpacity  = 0.5,
                  col          = "black",
                  opacity      = 1,
                  weight       = 3,
                  label        = ~paste0("District: ", DISTRICT),
                  layerId      = ~DISTRICT,
                  labelOptions = leaflet::labelOptions(
                                      noHide = F,
                                      style  = list(
                                        "color" = "black",
                                        "font-weight" = "1000")
                                    )
              ) %>%
              leaflet::addPolylines(
                  data        = fline,
                  stroke      = TRUE,
                  color       = "dodgerblue",
                  opacity     = 0.7
                  # layerId     = ~levelpathi
                  # fillColor   = "dodgerblue",
                  # fillOpacity = 1
                  ) %>% 
              leaflet::addCircleMarkers(
                  data        = fline_pts,
                  radius      = 6,
                  stroke      = FALSE,
                  color       = "black",
                  opacity     = 1,
                  fillColor   = "black",
                  fillOpacity = 0.7
                  ) %>% 
              leaflet::flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4])

          
             
          # # get points nearest to the furthest upstream and downstream main stem river segments
          # end_pts <- get_nearest_pts(
          #               flowlines = fline,
          #               pts       = fline_pts
          #               )
          # 
          # # get water right calls timeseries
          # call_df <- get_calls(
          #              df         = end_pts,
          #              start_date = Sys.Date() - 730,
          #              end_date   = Sys.Date()
          #              )

          
          # # render call date over time plot
          output$callDatePlot <- shiny::renderPlot({

             make_calls_plot_year(df = call_ts())

            })
          # 
          #  # render admin date map
          #  output$adminDatePlot <- shiny::renderPlot({
          #   
          #     make_date_map(
          #       lines = fline, 
          #       pts   = fline_pts
          #       )
          # 
          #   })
           # mapview::mapview(buff) + pt + wr_pts + catch + fline
          # mapview::mapview(pt, col.regions = "red") + 
          #   mapview::mapview(wr_pts, col.regions = "green") + 
          #   mapview::mapview(catch, col.regions = "yellow")  + 
          #   mapview::mapview(fline, color = "blue") +
          #   buff
          # lowest levelpath stream (mainstem)
          
          # mapview::mapview(pt, col.regions = "red") +
          #   mapview::mapview(end_pts, col.regions = "purple") +
          #   mapview::mapview(wr_pts, col.regions = "green") +
          #   mapview::mapview(catch, col.regions = "yellow")  +
          #   mapview::mapview(fline, color = "blue") 
            # mapview::mapview(min_fline, color = "orange") +
            # mapview::mapview(max_fline, color = "orange")
          }
  })



```


### Coords 
```{r}
shiny::verbatimTextOutput("mapCoords")
```

```{r context="server"}

# render district value box at start
output$mapCoords <- shiny::renderPrint({
  print(data.frame(
    lat = map_click()$lat,
    lng = map_click()$lng
    )
    )
})
```

### distID output
```{r}
shiny::verbatimTextOutput("distID")
```

```{r context="server"}

# render district value box at start
output$distID <- shiny::renderPrint({
  print(dist_id())
})
```

Row
-------------------------------------
    
### ggplot
```{r}
shiny::plotOutput("callDatePlot")
```

<!-- ### Binned date map -->
<!-- ```{r} -->
<!-- shiny::plotOutput("adminDatePlot") -->
<!-- ``` -->




