---
title: "CO Water Rights by district"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include = FALSE}
# Shiny & Flexdashboard packages
library(shiny)
library(flexdashboard)

# Data manipulation
# library(tidyr)
# library(dplyr)
library(dplyr)
library(ggplot2)
library(DT)

# Mapping packages
library(leaflet)
library(leafem)

# water data
# library(nhdplusTools)
# library(cdssr)

# Load function data_utils.R file
source('utils.R')
```

```{r context="server"}
# water rights net amounts spatial data
wr_pts         <- readRDS("water_right_netamounts_pts.rds")
wr_pts$gnis_id <- sub("^0+", "",wr_pts$gnis_id)

# uwdids     <- readRDS("data/unique_wdids.rds")
end_pts    <- readRDS("data/upstream_pts_district.rds")
# call_df    <- readRDS("data/upstream_call_analysis.rds")
# hucs       <- readRDS("data/huc4.rds")
# main_stem  <- readRDS("data/nhd_mainstems.rds")]

gnis_flines <- readRDS("data/nhd_gnis_id_flines.rds")

dists      <- sf::read_sf("data/water_districts_simple.geojson") 
  # dplyr::mutate(
  #   new_id = DISTRICT,
  #   map_id = paste0("map_id_", new_id)
  # )
# main_stem  <- readRDS("data/nhd_mainstems_district.rds")
# call_df    <- readRDS("data/upstream_call_analysis_district.rds")

# number of years to do call analysis on 
years <- 5

# base leaflet map
output$baseMap       <- renderLeaflet({ dist_basemap(shp = dists) })

```

```{r context="server"}
map_click <- shiny::reactive({
   input$baseMap_click
})
```

```{r context="server"}
dist_id <- shiny::reactive({
   as.numeric(input$baseMap_shape_click$id)
})
```

<!-- # ```{r context="server"} -->
<!-- # call_ts <- shiny::reactive({ -->
<!-- #    call_df[call_df$wdid == end_pts[end_pts$district == dist_id(),]$wdid, ] -->
<!-- #   # call_df[call_df$wdid == end_pts[end_pts$district == "01",]$wdid, ] -->
<!-- #    # call_df[call_df$wdid == end_pts[end_pts$huc4 == "1019",]$wdid, ] -->
<!-- # }) -->
<!-- #  -->
<!-- # ``` -->

```{r context="server"}
sub_flines <- shiny::reactive({
   gnis_flines[gnis_flines$district == dist_id(),]
   # sub_pts <- wr_pts[wr_pts$water_district == as.numeric("06"),]
})
```

```{r context="server"}
sub_pts <- shiny::reactive({
  wr_pts[wr_pts$water_district == dist_id(),]
  # if (is.null(sub_flines())) {
  #   tmp <- wr_pts[wr_pts$water_district == dist_id(),]
  #   tmp
  # } else {
  #   tmp <- wr_pts[wr_pts$water_district == dist_id(),]
  #   tmp <- tmp[tmp$gnis_id %in% sub_flines()$gnis_id, ]
  #   tmp
  #   }
  # sub_pts$gnis_id %in% sub_flines$gnis_id
   # sub_pts <- wr_pts[wr_pts$water_district == as.numeric("06"),]
})
 # unique(sub_pts$gnis_id) %in% unique(sub_flines$gnis_id)
 # wr_pts[wr_pts$wr_pts %in% sub_flines$gnis_id | wr_pts$water_district == as.numeric("06"), ]
 # 
 # 
 # 
 # unique(sub_flines$gnis_id)
 # unique(sub_pts$gnis_id)
 # unique(sub_flines$gnis_id) %in% sub("^0+", "",  unique(sub_pts$gnis_id))      
```

```{r context="server"}
dist_wdid <- shiny::reactive({
   sub_pts()$wdid
})

# cdss_data <- shiny::reactive({
#     if (!is.null(input$selectWDID)) {
#       cdssr::get_call_analysis_wdid(
#         wdid       = input$selectWDID,
#         admin_no   = "99999.00000",
#         start_date = Sys.Date() - 365*5,
#         end_date   = Sys.Date()
#         ) %>%
#         dplyr::mutate(
#           priority_date = dplyr::case_when(
#                             is.na(priority_date) ~ Sys.Date(),
#                             TRUE                 ~ as.Date(priority_date)
#                           )
#                         )
#     }
#   })
```

<!-- ```{r context="server"} -->
<!-- dist_wdid <- shiny::reactive({ -->
<!--    input$selectWDID -->
<!-- }) -->
<!-- ``` -->

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}

# shiny::selectInput(
#   "yearNum",
#   label = h3("Year"),
#   choices = 1990:2023,
#   selected = 2022
# )
shiny::selectizeInput(
  inputId  = "selectedYears",
  label    = h3("Year"),
  choices  = 2018:2022,
  selected = 2022,
  # choices  = 2018:2019,
  # selected = 2018,
  multiple = TRUE
  )
```

```{r}
shiny::selectizeInput(
  inputId  = "selectWDID",
  label    = h3("WDID"),
  # choices  = uwdids$wdid,
  choices  = NULL,
  selected = NULL,
  multiple = FALSE
  # options = list(plugins = list("remove_button"), 
  #                server = TRUE)
  )

shiny::observe({
 
  # Update the choices of input2 based on the reactive value
  shiny::updateSelectizeInput(session, "selectWDID", choices = dist_wdid())
   
})

```

1. Click on a HUC4 area within the interactive map in the top right panel

2. Adjust years of interest that will be highlighted in the top left plot.

<br>

The top left plot represents the most SENIOR right that makes a water right call throughout the year. Values lower on the Y axis correspond to a *more senior right* calling out. 

<br>

**The call analysis is done from the MOST upstream WDID at each HUC4's primary river mainstem using the most junior water right possible (admin number = "99999.00000").**  



Row
-------------------------------------

### Map 1
```{r}
leaflet::leafletOutput("baseMap")
```

```{r context="server"}
# Clicking on map 1 outputs Value boxes on both pages + catchment polygons + Dat table + success panel
# observeEvent(input$districtMapMLR_click, {
shiny::observeEvent(input$baseMap_shape_click, {

   if(is.null(dist_id())) {

     return(NULL)

   } else {

   # # if(!is.null(input$districtMapMLR_click)) {
   #    click <- input$districtMapMLR_click %>%
   #      data.frame() %>%
   #      dplyr::select(lat,lng)
      # print(click)

          pt <- sf::st_as_sf(
                    data.frame(
                      lat = map_click()$lat,
                      lng = map_click()$lng
                      ),
                    coords = c("lng", "lat"),
                    crs = 4326
                    )
          # 39.7792 -105.7214
          # 40.66392 -105.4837
          # 40.69808 -105.6
          # pt <- sf::st_as_sf(
          #           data.frame(
          #             lat = "39.978",
          #             lng =  "-105.6"
          #             ),
          #           coords = c("lng", "lat"),
          #           crs = 4326
          #           )

          print(paste0("Subsetting mainstems to HUC4: ",  dist_id()))

          print("Subsetting WDIDs to district area...")

          # subset to water district of interest
          sub_dist <- dists[dists$DISTRICT == dist_id(), ]
          
          # area_nhd <- nhdplusTools::get_nhdplus(
          #   AOI         = sub_dist,
          #   realization = c("flowline"),
          #   streamorder = 5
          #   )
          
          # nhdplusTools::navigate_network(
          #   start = pt, 
          #   
          # )
          
          
          # sub_pts  <- wr_pts[wr_pts$water_district == dist_id(), ]
          # sub_dist <- dists[dists$DISTRICT == as.numeric("06"), ]
          # sub_pts  <- wr_pts[wr_pts$water_district == as.numeric("06"), ]
          # sub_flines  <- gnis_flines[gnis_flines$district == as.numeric("06"), ]
          # sub_dist <- dists[dists$DISTRICT == as.numeric("06"), ]

          print("Updating leaflet map...")
          
          sub_pts2 = sub_pts()[sub_pts()$gnis_id %in% sub_flines()$gnis_id, ]
          # Create a continuous palette function
          fline_pal <- leaflet::colorFactor(
            palette = "RdYlBu",
            domain = sub_flines()$gnis_id
            )
          
          pt_pal <- leaflet::colorFactor(
            palette = "RdYlBu",
            domain = sub_pts2$gnis_id
            )
          
          message(paste0("Number Unique Point GNIS IDs: ", length(unique(sub_pts()$gnis_id))))
          message(paste0("Number Unique Fline GNIS IDs: ", length(unique(sub_flines()$gnis_id))))
          
          # dynamically alter leaflet map
          leaflet::leafletProxy("baseMap") %>%
              leaflet::clearMarkers() %>%
              leaflet::clearShapes() %>%
              leaflet::clearGroup(c("subdist")) %>%
                # leaflet::removeShape(layerId = levelpathi) %>%
                leaflet::addPolygons(
                      data         = dists,
                      fillColor    = 'white',
                      # fillColor = 'grey',
                      # fillColor = ~pal_fact(BASIN),
                      fillOpacity  = 0.7,
                      col          = "black",
                      opacity      = 1,
                      weight       = 2.5,
                      label        = ~paste0("District: ", DISTRICT),
                      layerId      = ~DISTRICT,
                      labelOptions = leaflet::labelOptions(
                                          noHide = F,
                                          style  = list(
                                            "color" = "black",
                                            "font-weight" = "1000")
                                        )
                  ) %>%
                leaflet::addPolygons(
                    data         = sub_dist,
                    fillColor    = '#3EB489',
                    # fillColor = 'grey',
                    # fillColor = ~pal_fact(BASIN),
                    fillOpacity  = 0.3,
                    col          = "black",
                    opacity      = 1,
                    weight       = 3,
                    group        = "subdist",
                    label        = ~paste0("District: ", DISTRICT),
                    layerId      = ~DISTRICT,
                    labelOptions = leaflet::labelOptions(
                                        noHide = F,
                                        style  = list(
                                          "color" = "black",
                                          "font-weight" = "1000")
                                      )
                ) %>%
              leaflet::addPolylines(
                data = sub_flines(),
                # data = sub_flines,
                color = ~fline_pal(gnis_id),
                opacity = 0.8,
                    label       = ~paste0("GNIS name: ", gnis_name, " - ( GNIS ID: ", gnis_id, " )"),
                labelOptions = leaflet::labelOptions(
                  noHide = F,
                  style  = list(
                    "color" = "black",
                    "font-weight" = "1000")
                ),
                stroke = T
              ) %>% 
            leaflet::addCircleMarkers(
                  # data        = sub_pts(),
                  # data = sub_pts()[sub_pts()$gnis_id %in% sub_flines()$gnis_id, ],
                 data        = sub_pts2,
                  radius      = 6,
                  stroke      = F,
                  color       = "black",
                  # width = 0.5,
                  opacity     = 0.6,
                  # fillColor   = "black",
                  fillColor = ~pt_pal(gnis_id),
                  fillOpacity = 0.7,
                  # label       = ~paste0("WDID: ", wdid, " - ( Approp date: ", appropriation_date, " )"),
                  label       = ~paste0("WDID: ", wdid, " - ( GNIS ID: ", gnis_id, " )"),
                  labelOptions = leaflet::labelOptions(
                                        noHide = F,
                                        style  = list(
                                          "color" = "black",
                                          "font-weight" = "1000")
                                      )
                  ) 
          
          
              # leaflet::addCircleMarkers(
              #         data        = sub_pts()[sub_pts()$wdid == input$selectWDID, ],
              #         radius      = 10,
              #         stroke      = FALSE,
              #         color       = "red",
              #         opacity     = 1,
              #         fillColor   = "red",
              #         fillOpacity = 0.7
              #         ) 
            # leaflet::addCircleMarkers(
            #   data = sub_pts$
            #   
            # )
            
             shiny::observe({

                  if(is.null(input$selectWDID)) {

                       return(NULL)

                     } else {
                       # poi    <- sub_pts()[sub_pts()$wdid == input$selectWDID, ]
                
                       # dm_net <- nhdplusTools::navigate_network(
                       #                start       = area_nhd$outlet, 
                       #                mode        = "DM",
                       #                distance_km = 10
                       #                )
                       # area_nhd <- nhdplusTools::get_nhdplus(
                       #   AOI          = pt,
                       #    realization = c("flowline", "outlet")
                       #    streamorder = 4
                       #    )
                       
                    leaflet::leafletProxy("baseMap") %>%
                        leaflet::clearGroup(c("singleWDID")) %>%
                        leaflet::addCircleMarkers(
                            # data        = sub_pts()[sub_pts()$wdid == input$selectWDID, ],
                            data        = sub_pts2[sub_pts2$wdid == input$selectWDID, ],  
                            radius      = 11,
                            stroke      = FALSE,
                            color       = "black",
                            opacity     = 0.9,
                            fillColor   = "black",
                            group       = "singleWDID",
                            fillOpacity = 0.7,
                            label       = ~paste0("WDID: ", wdid, " - ( Approp date: ", appropriation_date, " )"),
                            labelOptions = leaflet::labelOptions(
                                        noHide = F,
                                        style  = list(
                                          "color" = "black",
                                          "font-weight" = "1200")
                                      )
                            )
                    
                   if (!is.null(input$selectWDID)) {
                     
                     print(input$selectWDID)
                     
                     if(input$selectWDID != "") {
                            
                           calls <- cdssr::get_call_analysis_wdid(
                                              wdid       = input$selectWDID,
                                              # wdid = "0200509",
                                              admin_no   = "99999.00000",
                                              # start_date = "2018-01-01",
                                              # end_date   = "2019-12-31"
                                              start_date = Sys.Date() - 365*years,
                                              end_date   = Sys.Date()
                                            ) %>%
                                     dplyr::mutate(
                                              priority_date = dplyr::case_when(
                                                is.na(priority_date) ~ Sys.Date(),
                                                TRUE                 ~ as.Date(priority_date)
                                                # is.na(priority_date) ~ as.Date("2019-12-31"),
                                                # TRUE                 ~ as.Date(priority_date)
                                              )
                                              )

                              # min_date =  min(as.Date(sf::st_drop_geometry(wr_pts[wr_pts$wdid == "0200509", ])$appropriation_date))
                              min_date =  min(as.Date(sf::st_drop_geometry(wr_pts[wr_pts$wdid == input$selectWDID,
                                                                                  ])$appropriation_date))
                              
                              calls    = aggreg_weekly(df = calls)
                              
                         # render call date over time plot
                         output$rightographPlot <- shiny::renderPlot({
  
                            make_weekly_rightograph_plot(
                              df       = calls,
                              min_line = min_date, 
                              years    = input$selectedYears
                              )
  
                            })
                         
                                    # render call date over time plot
                         output$outpctPlot <- shiny::renderPlot({
  
                            make_weekly_out_pct_plot(
                              df       = calls,
                              years    = input$selectedYears
                              )
  
                            })

                     }
                   }
                     }
             })
              # leaflet::flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4])
            # shiny::observeEvent(input$selectWDID, {
          # shiny::observe({
          #       # Get the selected value of input1
          #       selected_input1 <- input$selectWDID
          #       # 
          #       # # Define the colors based on the selected value of input1
          #       colors <- ifelse(sub_pts()$id == selected_input1, "blue", "gray")
          #       
          #       print(paste0("Selectize input changed --> ", selected_input1))
          #       # Update the marker colors on the leaflet map
          #       leaflet::leafletProxy("baseMap") %>%
          #         leaflet::clearMarkers() %>%
          #         # leaflet::addCircleMarkers(
          #         #     data        = sub_pts()[sub_pts()$id != input$selectWDID,],
          #         #     radius      = 6,
          #         #     stroke      = FALSE,
          #         #     color       = "gray",
          #         #     opacity     = 1,
          #         #     fillOpacity = 0.7
          #         #     ) %>% 
          #         # leaflet::addCircleMarkers(
          #         #     data        = sub_pts()[sub_pts()$id == input$selectWDID,],
          #         #     radius      = 10,
          #         #     stroke      = FALSE,
          #         #     color       = "red",
          #         #     opacity     = 1,
          #         #     fillOpacity = 0.7
          #         #     ) 
          #           leaflet::addCircleMarkers(
          #             data        = sub_pts(),
          #             radius      = 10,
          #             stroke      = FALSE,
          #             # color       = "red",
          #             color = colors,
          #             opacity     = 1,
          #             fillOpacity = 0.7
          #             ) 
          #       })

          }
  })
# Listen to changes in the input value and update the marker color
# shiny::observe({
# shiny::observeEvent(input$selectWDID, {
#   # Get the selected value of input1
#   selected_input1 <- input$selectWDID
#   # 
#   # # Define the colors based on the selected value of input1
#   # colors <- ifelse(sub_pts()$id == selected_input1, "blue", "gray")
#   
#   print(paste0("Selectize input changed --> ", selected_input1))
#   # Update the marker colors on the leaflet map
#   leaflet::leafletProxy("baseMap") %>%
#     leaflet::clearMarkers() %>%
#     leaflet::addCircleMarkers(
#         data        = sub_pts()[sub_pts()$id != input$selectWDID,],
#         radius      = 6,
#         stroke      = FALSE,
#         color       = "gray",
#         opacity     = 1,
#         fillOpacity = 0.7
#         ) %>% 
#     leaflet::addCircleMarkers(
#         data        = sub_pts()[sub_pts()$id == input$selectWDID,],
#         radius      = 10,
#         stroke      = FALSE,
#         color       = "red",
#         opacity     = 1,
#         fillOpacity = 0.7
#         ) 
#   
# })

# shiny::observeEvent(input$selectWDID, {
# 
# 
#  calls <- cdssr::get_call_analysis_wdid(
#                                               wdid       = input$selectWDID,
#                                               # wdid = "0200509",
#                                               admin_no   = "99999.00000",
#                                               start_date = Sys.Date() - 365*5,
#                                               end_date   = Sys.Date()
#                                             ) %>% 
#                                      dplyr::mutate(
#                                               priority_date = dplyr::case_when(
#                                                 is.na(priority_date) ~ Sys.Date(),
#                                                 TRUE                 ~ as.Date(priority_date)
#                                               )
#                                             )
#                        # render call date over time plot 
#                        output$callDatePlot <- shiny::renderPlot({ 
#               
#                           make_single_call_plot(
#                             df    = calls,
#                             years = input$selectedYears
#                             ) 
#               
#                           }) 
#                        
# })
```

<!-- ### Coords  -->
<!-- ```{r} -->
<!-- shiny::verbatimTextOutput("mapCoords") -->
<!-- ``` -->

<!-- ```{r context="server"} -->

<!-- # render district value box at start -->
<!-- output$mapCoords <- shiny::renderPrint({ -->
<!--   print(data.frame( -->
<!--     lat = map_click()$lat, -->
<!--     lng = map_click()$lng -->
<!--     ) -->
<!--     ) -->
<!-- }) -->
<!-- ``` -->

<!-- ### distID output -->
<!-- ```{r} -->
<!-- shiny::verbatimTextOutput("distID") -->
<!-- ``` -->

<!-- ```{r context="server"} -->

<!-- # render district value box at start -->
<!-- output$distID <- shiny::renderPrint({ -->
<!--   print(dist_id()) -->
<!-- }) -->
<!-- ``` -->

Row
------------------------------------------------
### Table 
```{r}
DT::DTOutput("selectedWDIDinput")
```

```{r context="server"}

# render district value box at start
output$selectedWDIDinput <- DT::renderDT({
  
  # print(paste0("Selected WDID: ", input$selectWDID))
  # print("------------------------")
  
  # DT::datatable(sub_pts())
  # DT::datatable(sf::st_drop_geometry(sub_pts))
  DT::datatable(
    dplyr::select(sf::st_drop_geometry(sub_pts()), -comments),  
     style = "bootstrap",
     fillContainer = T,
      options       = list(
        pageLength   = 25,
        stateSave    = TRUE,
        lengthChange = T,
        dom          = "ft",
        pageLength = 10)
    )
     #  ) %>%
     # DT::formatRound(columns = c('Latitude', 'Longitude'),  digits = 2)
    
  # print("admin dates: ", cdss_data())
})
```

### Right-o-graph
```{r}
shiny::plotOutput("rightographPlot")
```

### Out of priority percent
```{r}
shiny::plotOutput("outpctPlot")
```

<!-- # --- -->
<!-- # title: "CO Water Rights" -->
<!-- # runtime: shiny -->
<!-- # output:  -->
<!-- #   flexdashboard::flex_dashboard: -->
<!-- #     orientation: rows -->
<!-- #     vertical_layout: fill -->
<!-- #     theme: flatly -->
<!-- # --- -->
<!-- #  -->
<!-- # ```{r setup, include = FALSE} -->
<!-- # # Shiny & Flexdashboard packages -->
<!-- # library(shiny) -->
<!-- # library(flexdashboard) -->
<!-- #  -->
<!-- # # Data manipulation -->
<!-- # # library(tidyr) -->
<!-- # # library(dplyr) -->
<!-- # library(dplyr) -->
<!-- # library(ggplot2) -->
<!-- #  -->
<!-- # # Mapping packages -->
<!-- # library(leaflet) -->
<!-- # library(leafem) -->
<!-- # library(dataRetrieval) -->
<!-- # # library(sf) -->
<!-- #  -->
<!-- # # water data -->
<!-- # # library(nhdplusTools) -->
<!-- # # library(cdssr) -->
<!-- #  -->
<!-- # # Load function data_utils.R file -->
<!-- # source('utils.R') -->
<!-- # ``` -->
<!-- #  -->
<!-- # ```{r context="server"} -->
<!-- # # water rights net amounts spatial data -->
<!-- # wr_pts     <- readRDS("data/water_right_netamounts_pts.rds") -->
<!-- # end_pts    <- readRDS("data/upstream_pts.rds") -->
<!-- # call_df    <- readRDS("data/upstream_call_analysis.rds") -->
<!-- #  -->
<!-- # hucs       <- readRDS("data/huc4.rds") -->
<!-- # main_stem  <- readRDS("data/nhd_mainstems_union.rds") -->
<!-- # # main_stem  <- readRDS("data/nhd_mainstems.rds") -->
<!-- #  -->
<!-- # # base leaflet map -->
<!-- # output$baseMap       <- renderLeaflet({ huc_basemap(shp = hucs) }) -->
<!-- #  -->
<!-- # ``` -->
<!-- #  -->
<!-- #  -->
<!-- # ```{r context="server"} -->
<!-- # map_click <- shiny::reactive({ -->
<!-- #    input$baseMap_click -->
<!-- # }) -->
<!-- # ``` -->
<!-- #  -->
<!-- # ```{r context="server"} -->
<!-- # huc_id <- shiny::reactive({ -->
<!-- #    input$baseMap_shape_click$id -->
<!-- # }) -->
<!-- # # tmp_huc <- "1019" -->
<!-- # ``` -->
<!-- #  -->
<!-- # ```{r context="server"} -->
<!-- # call_ts <- shiny::reactive({ -->
<!-- #    call_df[call_df$wdid == end_pts[end_pts$huc4 == huc_id(),]$wdid, ] -->
<!-- # }) -->
<!-- #  -->
<!-- # # call_ts <- call_df[call_df$wdid == end_pts[end_pts$huc4 == tmp_huc,]$wdid, ] -->
<!-- # ``` -->
<!-- #  -->
<!-- # ```{r context="server"} -->
<!-- # us_pt <- shiny::reactive({ -->
<!-- #    end_pts[end_pts$huc4 == huc_id(),] -->
<!-- # }) -->
<!-- # ``` -->
<!-- #  -->
<!-- # Inputs {.sidebar} -->
<!-- # ----------------------------------------------------------------------- -->
<!-- #  -->
<!-- # ```{r} -->
<!-- #  -->
<!-- # # shiny::selectInput( -->
<!-- # #   "yearNum", -->
<!-- # #   label = h3("Year"), -->
<!-- # #   choices = 1990:2023, -->
<!-- # #   selected = 2022 -->
<!-- # # ) -->
<!-- #  -->
<!-- # shiny::selectizeInput( -->
<!-- #   inputId  = "selectedYears", -->
<!-- #   label    = h3("Year"), -->
<!-- #   choices  = 1990:2022, -->
<!-- #   selected = 2022, -->
<!-- #   multiple = TRUE -->
<!-- #   ) -->
<!-- # ``` -->
<!-- #  -->
<!-- # 1. Click on a HUC4 area within the interactive map in the top right panel -->
<!-- #  -->
<!-- # 2. Adjust years of interest that will be highlighted in the top left plot. -->
<!-- #  -->
<!-- # <br> -->
<!-- #  -->
<!-- # The top left plot represents the most SENIOR right that makes a water right call throughout the year. Values lower on the Y axis correspond to a *more senior right* calling out.  -->
<!-- #  -->
<!-- # <br> -->
<!-- #  -->
<!-- # **The call analysis is done from the MOST upstream WDID at each HUC4's primary river mainstem using the most junior water right possible (admin number = "99999.00000").**   -->


<!-- Row -->
<!-- ------------------------------------- -->

<!-- ### Priority date vs date (year selection) -->
<!-- ```{r} -->
<!-- shiny::plotOutput("callHighlightPlot") -->
<!-- ``` -->

<!-- ### Map 1 -->
<!-- ```{r} -->
<!-- leaflet::leafletOutput("baseMap") -->
<!-- ``` -->

<!-- # ```{r context="server"} -->
<!-- # # Clicking on map 1 outputs Value boxes on both pages + catchment polygons + Dat table + success panel -->
<!-- # # observeEvent(input$districtMapMLR_click, { -->
<!-- # shiny::observeEvent(input$baseMap_shape_click, { -->
<!-- #    -->
<!-- #    # if(is.null(huc_id())) { -->
<!-- #    #    -->
<!-- #    #   return(NULL) -->
<!-- #    #    -->
<!-- #    # } else { -->
<!-- #       -->
<!-- #    # # if(!is.null(input$districtMapMLR_click)) { -->
<!-- #    #    click <- input$districtMapMLR_click %>% -->
<!-- #    #      data.frame() %>% -->
<!-- #    #      dplyr::select(lat,lng) -->
<!-- #       # print(click) -->
<!-- #  -->
<!-- #           pt <- sf::st_as_sf( -->
<!-- #                     data.frame( -->
<!-- #                       lat = map_click()$lat, -->
<!-- #                       lng = map_click()$lng -->
<!-- #                       ), -->
<!-- #                     coords = c("lng", "lat"), -->
<!-- #                     crs = 4326 -->
<!-- #                     ) -->
<!-- #           # 39.7792 -105.7214 -->
<!-- #           # # 40.66392 -105.4837 -->
<!-- #           # 40.69808 -105.6 -->
<!-- #           # pt <- sf::st_as_sf( -->
<!-- #           #           data.frame( -->
<!-- #           #             lat = "40.69808", -->
<!-- #           #             lng =  "-105.6" -->
<!-- #           #             ), -->
<!-- #           #           coords = c("lng", "lat"), -->
<!-- #           #           crs = 4326 -->
<!-- #           #           ) -->
<!-- #            -->
<!-- #           print(paste0("Subsetting mainstems to HUC4: ",  huc_id())) -->
<!-- #            -->
<!-- #           # select mainstem of HUC4 area -->
<!-- #           fline <- -->
<!-- #             main_stem %>% -->
<!-- #             dplyr::filter(huc4 == huc_id()) -->
<!-- #             # dplyr::filter(huc4 == tmp_huc) -->
<!-- #            -->
<!-- #           # buffer bounds of mainstem for map fly to zoom -->
<!-- #           bounds <- -->
<!-- #             # buff %>% -->
<!-- #             fline %>% -->
<!-- #             # sf::st_buffer(5250) %>% -->
<!-- #             sf::st_bbox() %>% -->
<!-- #             as.vector() -->
<!-- #   -->
<!-- #           print("Buffering mainstem...") -->
<!-- #            -->
<!-- #           # buffer around mainstem to get points within -->
<!-- #           fline_buff <- sf::st_as_sf( -->
<!-- #                           sf::st_cast( -->
<!-- #                             sf::st_union( -->
<!-- #                               sf::st_buffer( -->
<!-- #                                 sf::st_transform( -->
<!-- #                                   fline, -->
<!-- #                                   5070 -->
<!-- #                                   ), -->
<!-- #                                 1609.3 -->
<!-- #                                 ) -->
<!-- #                               ), -->
<!-- #                             "POLYGON" -->
<!-- #                             ) -->
<!-- #                           ) -->
<!-- #            -->
<!-- #           print("Subsetting WDIDs to mainstem buffer...") -->
<!-- #  -->
<!-- #           # Water rights points around main flowline -->
<!-- #           fline_pts <- sf::st_transform( -->
<!-- #                           sf::st_filter( -->
<!-- #                             sf::st_transform( -->
<!-- #                               dplyr::filter(wr_pts, huc4 == huc_id()), -->
<!-- #                               # dplyr::filter(wr_pts, huc4 == tmp_huc), -->
<!-- #                               5070 -->
<!-- #                               ) , -->
<!-- #                             fline_buff -->
<!-- #                             ), -->
<!-- #                             4326 -->
<!-- #                           ) -->
<!-- #           # 1401  -->
<!-- #           # subset to HUC4 of interest -->
<!-- #           sub_huc <- hucs[hucs$huc4 == huc_id(), ] -->
<!-- #           # sub_huc <- hucs[hucs$huc4 == tmp_huc, ] -->
<!-- #            -->
<!-- #           print("Updating leaflet map...") -->
<!-- #            -->
<!-- #           # dynamically alter leaflet map  -->
<!-- #           leaflet::leafletProxy("baseMap") %>% -->
<!-- #               leaflet::clearMarkers() %>% -->
<!-- #               leaflet::clearGroup(c("subhucs", "mainstems")) %>% -->
<!-- #               # leaflet::clearShapes() %>% -->
<!-- #               # leaflet::removeShape(layerId = levelpathi) %>% -->
<!-- #               leaflet::addPolygons( -->
<!-- #                     data         = hucs, -->
<!-- #                     fillColor    = 'white', -->
<!-- #                     # fillColor = 'grey', -->
<!-- #                     # fillColor = ~pal_fact(BASIN), -->
<!-- #                     fillOpacity  = 0.7, -->
<!-- #                     col          = "black", -->
<!-- #                     opacity      = 1, -->
<!-- #                     weight       = 2.5, -->
<!-- #                     label        = ~paste0("HUC4: ", huc4), -->
<!-- #                     layerId      = ~huc4, -->
<!-- #                     labelOptions = leaflet::labelOptions( -->
<!-- #                                         noHide = F, -->
<!-- #                                         style  = list( -->
<!-- #                                           "color" = "black", -->
<!-- #                                           "font-weight" = "1000") -->
<!-- #                                       ) -->
<!-- #                 ) %>% -->
<!-- #               leaflet::addPolygons( -->
<!-- #                   data         = sub_huc, -->
<!-- #                   fillColor    = '#3EB489', -->
<!-- #                   # fillColor = 'grey', -->
<!-- #                   # fillColor = ~pal_fact(BASIN), -->
<!-- #                   fillOpacity  = 0.5, -->
<!-- #                   col          = "black", -->
<!-- #                   opacity      = 1, -->
<!-- #                   weight       = 3, -->
<!-- #                   group        = "subhucs", -->
<!-- #                   label        = ~paste0("HUC4: ", huc4), -->
<!-- #                   layerId      = ~huc4, -->
<!-- #                   labelOptions = leaflet::labelOptions( -->
<!-- #                                       noHide = F, -->
<!-- #                                       style  = list( -->
<!-- #                                         "color" = "black", -->
<!-- #                                         "font-weight" = "1000") -->
<!-- #                                     ) -->
<!-- #               ) %>% -->
<!-- #               leaflet::addPolylines( -->
<!-- #                   data        = fline, -->
<!-- #                   stroke      = TRUE, -->
<!-- #                   color       = "dodgerblue", -->
<!-- #                   opacity     = 0.9, -->
<!-- #                   group       = "mainstems" -->
<!-- #                   # layerId     = ~levelpathi -->
<!-- #                   # fillColor   = "dodgerblue", -->
<!-- #                   # fillOpacity = 1 -->
<!-- #                   ) %>%  -->
<!-- #               leaflet::addCircleMarkers( -->
<!-- #                   data        = fline_pts, -->
<!-- #                   radius      = 5, -->
<!-- #                   stroke      = FALSE, -->
<!-- #                   color       = "black", -->
<!-- #                   opacity     = 1, -->
<!-- #                   fillColor   = "black", -->
<!-- #                   fillOpacity = 0.5, -->
<!-- #                   label        = ~paste0("WDID: ", wdid), -->
<!-- #                   layerId      = ~wdid, -->
<!-- #                   labelOptions = leaflet::labelOptions( -->
<!-- #                                       noHide = F, -->
<!-- #                                       style  = list( -->
<!-- #                                         "color" = "black", -->
<!-- #                                         "font-weight" = "1000") -->
<!-- #                                     ) -->
<!-- #                   ) %>%  -->
<!-- #               leaflet::addCircleMarkers( -->
<!-- #                   data        = us_pt(), -->
<!-- #                   radius      = 6, -->
<!-- #                   stroke      = FALSE, -->
<!-- #                   color       = "red", -->
<!-- #                   opacity     = 1, -->
<!-- #                   fillColor   = "red", -->
<!-- #                   fillOpacity = 0.9, -->
<!-- #                   label        = ~paste0("WDID: ", wdid), -->
<!-- #                   layerId      = ~wdid, -->
<!-- #                   labelOptions = leaflet::labelOptions( -->
<!-- #                                       noHide = F, -->
<!-- #                                       style  = list( -->
<!-- #                                         "color" = "black", -->
<!-- #                                         "font-weight" = "1000") -->
<!-- #                                     ) -->
<!-- #                   ) %>%  -->
<!-- #               leaflet::flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4]) -->
<!-- #  -->
<!-- #           # # render call date over time plot -->
<!-- #           output$callDatePlot <- shiny::renderPlot({ -->
<!-- #  -->
<!-- #              make_calls_plot_year(df = call_ts()) -->
<!-- #              -->
<!-- #             }) -->
<!-- #            -->
<!-- #            -->
<!-- #  -->
<!-- #            # render admin date map -->
<!-- #            output$adminDatePlot <- shiny::renderPlot({ -->
<!-- #  -->
<!-- #               make_date_map( -->
<!-- #                 lines = fline, -->
<!-- #                 pts   = fline_pts -->
<!-- #                 ) -->
<!-- #  -->
<!-- #             }) -->
<!-- #             -->
<!-- #            shiny::observeEvent(input$selectedYears, { -->
<!-- #    -->
<!-- #    -->
<!-- #               # render call date over time plot -->
<!-- #               output$callHighlightPlot <- shiny::renderPlot({ -->
<!-- #      -->
<!-- #                  make_highlight_calls_plot( -->
<!-- #                    df    = call_ts(), -->
<!-- #                    years = input$selectedYears -->
<!-- #                    ) -->
<!-- #                  -->
<!-- #                 }) -->
<!-- #                -->
<!-- #               }) -->
<!-- #  -->
<!-- # }) -->
<!-- #            # mapview::mapview(buff) + pt + wr_pts + catch + fline -->
<!-- #           # mapview::mapview(pt, col.regions = "red") +  -->
<!-- #           #   mapview::mapview(wr_pts, col.regions = "green") +  -->
<!-- #           #   mapview::mapview(catch, col.regions = "yellow")  +  -->
<!-- #           #   mapview::mapview(fline, color = "blue") + -->
<!-- #           #   buff -->
<!-- #           # lowest levelpath stream (mainstem) -->
<!-- #            -->
<!-- #           # mapview::mapview(pt, col.regions = "red") + -->
<!-- #           #   mapview::mapview(end_pts, col.regions = "purple") + -->
<!-- #           #   mapview::mapview(wr_pts, col.regions = "green") + -->
<!-- #           #   mapview::mapview(catch, col.regions = "yellow")  + -->
<!-- #           #   mapview::mapview(fline, color = "blue")  -->
<!-- #             # mapview::mapview(min_fline, color = "orange") + -->
<!-- #             # mapview::mapview(max_fline, color = "orange") -->
<!-- #           # } -->
<!-- #   # }) -->
<!-- #  -->
<!-- #  -->
<!-- #  -->
<!-- # ``` -->


<!-- ### Coords -->
<!-- ```{r} -->
<!-- shiny::verbatimTextOutput("mapCoords") -->
<!-- ``` -->

<!-- ```{r context="server"} -->

<!-- # render district value box at start -->
<!-- output$mapCoords <- shiny::renderPrint({ -->
<!--   print(data.frame( -->
<!--     lat = map_click()$lat, -->
<!--     lng = map_click()$lng -->
<!--     ) -->
<!--     ) -->
<!-- }) -->
<!-- ``` -->

<!-- ### HUC ID output -->
<!-- ```{r} -->
<!-- shiny::verbatimTextOutput("hucID") -->
<!-- ``` -->

<!-- ```{r context="server"} -->

<!-- # render district value box at start -->
<!-- output$hucID <- shiny::renderPrint({ -->
<!--   print(huc_id()) -->
<!-- }) -->
<!-- ``` -->

<!-- ### Call ts output -->
<!-- ```{r} -->
<!-- shiny::verbatimTextOutput("callTS") -->
<!-- ``` -->

<!-- ```{r context="server"} -->

<!-- # render district value box at start -->
<!-- output$callTS <- shiny::renderPrint({ -->
<!--   print(call_ts()) -->
<!-- }) -->
<!-- ``` -->

<!-- Row -->
<!-- ------------------------------------- -->

<!-- ### Priority date vs. date (year facets) -->
<!-- ```{r} -->
<!-- shiny::plotOutput("callDatePlot") -->
<!-- ``` -->

<!-- ### Binned date map -->
<!-- ```{r} -->
<!-- shiny::plotOutput("adminDatePlot") -->
<!-- ``` -->

<!-- --- -->
<!-- title: "CO Water Rights" -->
<!-- runtime: shiny -->
<!-- output:  -->
<!--   flexdashboard::flex_dashboard: -->
<!--     orientation: rows -->
<!--     vertical_layout: fill -->
<!-- --- -->

<!-- ```{r setup, include = FALSE} -->
<!-- # Shiny & Flexdashboard packages -->
<!-- library(shiny) -->
<!-- library(flexdashboard) -->

<!-- # Data manipulation -->
<!-- # library(tidyr) -->
<!-- # library(dplyr) -->
<!-- library(dplyr) -->
<!-- library(ggplot2) -->

<!-- # Mapping packages -->
<!-- library(leaflet) -->
<!-- library(leafem) -->
<!-- library(dataRetrieval) -->
<!-- # library(sf) -->

<!-- # water data -->
<!-- # library(nhdplusTools) -->
<!-- # library(cdssr) -->

<!-- # Load function data_utils.R file -->
<!-- source('utils.R') -->
<!-- ``` -->

<!-- ```{r context="server"} -->
<!-- # water rights net amounts spatial data -->
<!-- wr_pts <- readRDS("water_right_netamounts_pts.rds") -->

<!-- # base leaflet map -->
<!-- output$baseMap       <- renderLeaflet({ basemap() }) -->

<!-- ``` -->

<!-- Row -->
<!-- ------------------------------------- -->

<!-- ### Map 1 -->
<!-- ```{r} -->
<!-- leaflet::leafletOutput("baseMap") -->
<!-- ``` -->

<!-- ```{r context="server"} -->
<!-- map_click <- shiny::reactive({ -->
<!--    input$baseMap_click -->
<!-- }) -->
<!-- ``` -->

<!-- ```{r context="server"} -->
<!-- # Clicking on map 1 outputs Value boxes on both pages + catchment polygons + Dat table + success panel -->
<!-- # observeEvent(input$districtMapMLR_click, { -->
<!-- shiny::observeEvent(input$baseMap_click, { -->

<!--    # # if(!is.null(input$districtMapMLR_click)) { -->
<!--    #    click <- input$districtMapMLR_click %>% -->
<!--    #      data.frame() %>% -->
<!--    #      dplyr::select(lat,lng) -->
<!--       # print(click) -->

<!--       pt <- sf::st_as_sf( -->
<!--                 data.frame( -->
<!--                   lat = map_click()$lat, -->
<!--                   lng = map_click()$lng -->
<!--                   ), -->
<!--                 coords = c("lng", "lat"), -->
<!--                 crs = 4326 -->
<!--                 ) -->
<!--           # 39.7792 -105.7214 -->
<!--           # # # 39.445 -105.176 -->
<!--           # # # 40.27937 -105.8168 -->
<!--           # # 40.66392 -105.4837 -->
<!--       # 40.69808 -105.6 -->
<!--           # pt <- sf::st_as_sf( -->
<!--           #           data.frame( -->
<!--           #             lat = "40.69808", -->
<!--           #             lng =  "-105.6" -->
<!--           #             ), -->
<!--           #           coords = c("lng", "lat"), -->
<!--           #           crs = 4326 -->
<!--           #           ) -->

<!--           # buffer to search area for NHD features -->
<!--           # buff <- sf::st_buffer(pt, 1500) -->
<!--           # buff <- sf::st_transform( -->
<!--           #             sf::st_buffer( -->
<!--           #               sf::st_transform(pt, 5070), -->
<!--           #             1609.3*7 -->
<!--           #             ), -->
<!--           #             4326 -->
<!--           #             ) -->
<!--           # sf::st_transform(pt, 5070) -->
<!--           # # # buffer bounds -->
<!--           # bounds <- -->
<!--           #   # buff %>% -->
<!--           #   buff %>% -->
<!--           #   # sf::st_buffer(5250) %>% -->
<!--           #   sf::st_bbox() %>% -->
<!--           #   as.vector() -->

<!--           # # Get flowlines and catchment geometries -->
<!--           # area_nhd <- nhdplusTools::get_nhdplus( -->
<!--           #   AOI         = buff, -->
<!--           #   realization = c("flowline", "catchment"), -->
<!--           #   streamorder = 3 -->
<!--           #   ) -->

<!--           #  # Get flowlines and catchment geometries -->
<!--           # area_nhd <- nhdplusTools::get_nhdplus( -->
<!--           #   AOI         = buff, -->
<!--           #   realization = c("flowline", "catchment"), -->
<!--           #   streamorder = 3 -->
<!--           #   ) -->
<!--           # area_nhd$flowline %>%  -->
<!--           #   dplyr::mutate( -->
<!--           #     streamorde = as.character(streamorde), -->
<!--           #     streamleve = as.character(streamleve) -->
<!--           #                 ) %>%  -->
<!--           #   sf::st_buffer(1609.3) %>%  -->
<!--           # ggplot2::ggplot() + -->
<!--           #   ggplot2::geom_sf(ggplot2::aes(color = streamleve)) -->

<!--           # # NHD flowlines -->
<!--           # fline <- area_nhd$flowline -->
<!--           #  -->
<!--           # # NHD Catchment -->
<!--           # catch <- area_nhd$catchment -->

<!--           fline <- get_us_net( -->
<!--             pt       = pt,  -->
<!--             distance = 60 -->
<!--             ) -->

<!--             # # buffer bounds -->
<!--           bounds <- -->
<!--             # buff %>% -->
<!--             fline %>% -->
<!--             # sf::st_buffer(5250) %>% -->
<!--             sf::st_bbox() %>% -->
<!--             as.vector() -->

<!--           # # main stem of flowlines -->
<!--           # main_stem <- fline[fline$streamleve == min(fline$streamleve), ] -->

<!--           # buffer around mainstem to get points within -->
<!--           fline_buff <- sf::st_as_sf( -->
<!--                           sf::st_cast( -->
<!--                             sf::st_union( -->
<!--                               sf::st_buffer( -->
<!--                                 sf::st_transform( -->
<!--                                   fline, -->
<!--                                   5070 -->
<!--                                   ), -->
<!--                                 1609.3 -->
<!--                                 ) -->
<!--                               ), -->
<!--                             "POLYGON" -->
<!--                             ) -->
<!--                           ) -->

<!--           # Water rights points around main flowline -->
<!--           fline_pts <- sf::st_transform( -->
<!--                           sf::st_filter( -->
<!--                             sf::st_transform( -->
<!--                               wr_pts,  -->
<!--                               5070 -->
<!--                               ) , -->
<!--                             fline_buff -->
<!--                             ), -->
<!--                             4326 -->
<!--                           ) -->

<!--           # get points nearest to the furthest upstream and downstream main stem river segments -->
<!--           end_pts <- get_nearest_pts( -->
<!--                         flowlines = fline, -->
<!--                         pts       = fline_pts -->
<!--                         ) -->

<!--           # get water right calls timeseries -->
<!--           call_df <- get_calls( -->
<!--                        df         = end_pts, -->
<!--                        start_date = Sys.Date() - 730, -->
<!--                        end_date   = Sys.Date() -->
<!--                        ) -->

<!--           # min_fline <- fline[fline$streamleve == min(fline$streamleve), ] -->

<!--           # min_fline <- sf::st_as_sf( -->
<!--           #               sf::st_cast( -->
<!--           #                 sf::st_union( -->
<!--           #                   sf::st_buffer( -->
<!--           #                     sf::st_transform( -->
<!--           #                       fline[fline$streamleve == min(fline$streamleve), ], -->
<!--           #                       5070 -->
<!--           #                       ), -->
<!--           #                     1609.3 -->
<!--           #                     ) -->
<!--           #                   ), -->
<!--           #                 "POLYGON" -->
<!--           #                 ) -->
<!--           #               ) -->

<!--           # # get Water right points -->
<!--           # wr_pts <- get_wr_pts(x = min_fline, buffer = 10) -->

<!--           # # Get flowlines and catchment geometries -->
<!--           # area_nhd <- nhdplusTools::get_nhdplus( -->
<!--           #   AOI         = buff, -->
<!--           #   realization = c("flowline", "catchment"), -->
<!--           #   streamorder = 3 -->
<!--           #   ) -->
<!--           #  -->
<!--           # # NHD flowlines -->
<!--           # fline <- area_nhd$flowline -->
<!--           #  -->
<!--           # # NHD Catchment -->
<!--           # catch <- area_nhd$catchment -->

<!--           # mapview::mapview(buff) + pt + wr_pts + catch + fline -->

<!--           # # get points nearest to the furthest upstream and downstream main stem river segments -->
<!--           # end_pts <- get_nearest_pts( -->
<!--           #               flowlines = fline, -->
<!--           #               pts       = wr_pts -->
<!--           #               ) -->

<!--           # # get points nearest to the furthest upstream and downstream main stem river segments -->
<!--           # main_stem <- get_main_stem( -->
<!--           #               flowlines = fline -->
<!--           #               ) -->

<!--           # # get points nearest to the furthest upstream and downstream main stem river segments -->
<!--           # end_pts <- get_nearest_pts( -->
<!--           #               flowlines = main_stem, -->
<!--           #               pts       = wr_pts -->
<!--           #               ) -->

<!--           # # get water right calls timeseries -->
<!--           # call_df <- get_calls( -->
<!--           #   df         = end_pts, -->
<!--           #   start_date = Sys.Date() - 365, -->
<!--           #   end_date   = Sys.Date() -->
<!--           #   ) -->
<!--           #  -->
<!--           # call_plot <- make_calls_plot(df = call_df) -->

<!--           # render call date over time plot -->
<!--           output$callDatePlot <- shiny::renderPlot({ -->

<!--              make_calls_plot(df = call_df) -->

<!--             }) -->

<!--            # render admin date map -->
<!--            output$adminDatePlot <- shiny::renderPlot({ -->

<!--               make_date_map( -->
<!--                 lines = fline,  -->
<!--                 pts   = fline_pts -->
<!--                 ) -->

<!--             }) -->
<!--            # mapview::mapview(buff) + pt + wr_pts + catch + fline -->
<!--           # mapview::mapview(pt, col.regions = "red") +  -->
<!--           #   mapview::mapview(wr_pts, col.regions = "green") +  -->
<!--           #   mapview::mapview(catch, col.regions = "yellow")  +  -->
<!--           #   mapview::mapview(fline, color = "blue") + -->
<!--           #   buff -->
<!--           # lowest levelpath stream (mainstem) -->

<!--           # mapview::mapview(pt, col.regions = "red") + -->
<!--           #   mapview::mapview(end_pts, col.regions = "purple") + -->
<!--           #   mapview::mapview(wr_pts, col.regions = "green") + -->
<!--           #   mapview::mapview(catch, col.regions = "yellow")  + -->
<!--           #   mapview::mapview(fline, color = "blue")  -->
<!--             # mapview::mapview(min_fline, color = "orange") + -->
<!--             # mapview::mapview(max_fline, color = "orange") -->



<!--           leaflet::leafletProxy("baseMap") %>% -->
<!--               leaflet::clearMarkers() %>% -->
<!--               leaflet::clearShapes() %>% -->
<!--               # leaflet::addPolygons( -->
<!--               #   data        = catch, -->
<!--               #   color       = "grey", -->
<!--               #   opacity     = 0.8,  -->
<!--               #   fillColor   = "white", -->
<!--               #   fillOpacity = 0.5, -->
<!--               #   stroke      = FALSE -->
<!--               #   ) %>% -->
<!--               leaflet::addPolylines( -->
<!--                 data        = fline, -->
<!--                 stroke      = TRUE, -->
<!--                 color       = "dodgerblue", -->
<!--                 opacity     = 0.7 -->
<!--                 # fillColor   = "dodgerblue", -->
<!--                 # fillOpacity = 1 -->
<!--                 ) %>%  -->
<!--               # leaflet::addPolylines( -->
<!--               #   data        = fline[fline$streamleve != min(fline$streamleve), ], -->
<!--               #   stroke      = TRUE, -->
<!--               #   color       = "dodgerblue", -->
<!--               #   opacity     = 0.7 -->
<!--               #   # fillColor   = "dodgerblue", -->
<!--               #   # fillOpacity = 1 -->
<!--               #   ) %>% -->
<!--              # leaflet::addPolylines( -->
<!--              #    data        = fline[fline$streamleve == min(fline$streamleve), ], -->
<!--              #    stroke      = TRUE, -->
<!--              #    color       = "navy", -->
<!--              #    opacity     = 0.9 -->
<!--              #    # fillColor   = "navy", -->
<!--              #    # fillOpacity = 1 -->
<!--              #    ) %>%  -->
<!--               # leaflet::addCircleMarkers( -->
<!--               #   data        = wr_pts[!wr_pts$wdid %in% end_pts$wdid, ], -->
<!--               #   radius      = 7, -->
<!--               #   stroke      = FALSE, -->
<!--               #   # color       = "black", -->
<!--               #   # opacity     = 1, -->
<!--               #   fillColor   = "black", -->
<!--               #   fillOpacity = 0.7 -->
<!--               #   ) %>%  -->
<!--               leaflet::addCircleMarkers( -->
<!--                 data        = fline_pts[!fline_pts$wdid %in% end_pts$wdid, ], -->
<!--                 radius      = 7, -->
<!--                 stroke      = FALSE, -->
<!--                 color       = "black", -->
<!--                 opacity     = 1, -->
<!--                 fillColor   = "black", -->
<!--                 fillOpacity = 0.7 -->
<!--                 ) %>%  -->
<!--               leaflet::addCircleMarkers( -->
<!--                 data        = end_pts, -->
<!--                 radius      = 7, -->
<!--                 stroke      = FALSE, -->
<!--                 # color       = "dodgerblue", -->
<!--                 # opacity     = 1, -->
<!--                 fillColor   = "red", -->
<!--                 fillOpacity = 0.7 -->
<!--                 ) %>%  -->
<!--               leaflet::flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4]) -->
<!--        }) -->


<!-- ``` -->


<!-- ### Coords  -->
<!-- ```{r} -->
<!-- shiny::verbatimTextOutput("mapCoords") -->
<!-- ``` -->

<!-- ```{r context="server"} -->

<!-- # render district value box at start -->
<!-- output$mapCoords <- shiny::renderPrint({ -->
<!--   print(data.frame( -->
<!--     lat = map_click()$lat, -->
<!--     lng = map_click()$lng -->
<!--     ) -->
<!--     ) -->
<!-- }) -->
<!-- ``` -->

<!-- Row -->
<!-- ------------------------------------- -->

<!-- ### ggplot -->
<!-- ```{r} -->
<!-- shiny::plotOutput("callDatePlot") -->
<!-- ``` -->

<!-- ### Binned date map -->
<!-- ```{r} -->
<!-- shiny::plotOutput("adminDatePlot") -->
<!-- ``` -->




